name: Deploy to Cloud

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.HOST }}
          key: ${{ secrets.EC2_PEM }}
          port: 22
          source: .
          target: "/home/${{ secrets.HOST }}/practice"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.HOST }}
          key: ${{ secrets.EC2_PEM }}
          port: 22
          script: |
            cd /home/${{ secrets.HOST }}/practice
            docker-compose up -d --build --remove-orphans
