name: Deploy to Cloud

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM }}
          port: 22
          source: .
          target: "/home/${{ secrets.EC2_USERNAME }}/practice"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM }}
          port: 22
          script: |
            cd /home/${{ secrets.EC2_USERNAME }}/practice
            # Force stop and remove all containers for this project
            docker compose down --remove-orphans --volumes
            # Remove any lingering containers with the same name (failsafe)
            docker container rm -f batalion 2>/dev/null || true
            # Clean up unused images to free space
            docker image prune -f
            # Start fresh containers
            docker compose up -d --build --remove-orphans